## Lecture 1.3: Distributions and Sampling in PyTorch

In [8]:
import torch
import torch.distributions as dist

In [9]:
## Lets create a Bernoulli distribution
bernoulli = dist.Bernoulli(torch.tensor([0.5]))
print(bernoulli)

## Sample from the distribution
for _ in range(10):
    print(bernoulli.sample())

Bernoulli(probs: tensor([0.5000]))
tensor([1.])
tensor([1.])
tensor([1.])
tensor([1.])
tensor([1.])
tensor([1.])
tensor([0.])
tensor([1.])
tensor([0.])
tensor([0.])


In [12]:
samples = [bernoulli.sample() for _ in range(1000)]
print(f"Mean: {torch.mean(torch.stack(samples))}")
print(f"Variance: {torch.var(torch.stack(samples))}")

Mean: 0.5239999890327454
Variance: 0.24967367947101593


In [13]:
## Lets create a Gaussian distribution
normal = dist.Normal(torch.tensor([0.0]), torch.tensor([1.0]))
for _ in range(10):
    print(normal.sample())

tensor([-0.7229])
tensor([1.1160])
tensor([-1.4577])
tensor([0.9672])
tensor([1.1499])
tensor([1.7813])
tensor([0.5224])
tensor([0.0227])
tensor([-0.2280])
tensor([1.6521])


In [14]:
samples = [normal.sample() for _ in range(1000)]
print(f"Mean: {torch.mean(torch.stack(samples))}")
print(f"Variance: {torch.var(torch.stack(samples))}")

Mean: 0.029531698673963547
Variance: 1.028912901878357
