## Lecture 1.8: Tensors in PyTorch

In [1]:
import torch

In [2]:
a = torch.tensor([1.0, 2, 3], dtype=torch.float32)
print(a)
# print(a.shape)
# print(a.ndim)
# print(a.dtype)

tensor([1., 2., 3.])


In [3]:
b = torch.rand([3, 3, 3], dtype=torch.float32)
print(b)

tensor([[[0.3613, 0.0599, 0.6705],
         [0.8989, 0.8875, 0.0209],
         [0.6869, 0.3221, 0.0412]],

        [[0.3156, 0.4307, 0.0737],
         [0.7950, 0.7931, 0.5011],
         [0.5063, 0.5528, 0.0159]],

        [[0.8925, 0.5243, 0.3097],
         [0.4249, 0.3511, 0.0994],
         [0.7861, 0.8516, 0.4885]]])


In [4]:
from PIL import Image
import numpy as np

img = Image.open('cat.jpg')
c = torch.as_tensor(np.array(img))
# print(c.shape)
print(c.dtype)

torch.uint8


In [5]:
a = torch.arange(10)
b = torch.ones(10)
print(f'{a = }')
print(f'{b = }')
print(f'{a + b = }')
print(f'{a ** (2*b) =}')

a = tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
b = tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
a + b = tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
a ** (2*b) =tensor([ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.])


In [7]:
a = torch.rand(4)
b = torch.rand(5)
print(a + b)

RuntimeError: The size of tensor a (4) must match the size of tensor b (5) at non-singleton dimension 0

In [9]:
a = torch.rand(1_000_000_000)
b = torch.rand(1_000_000_000)
c = a + b

In [ ]:
%timeit c = a + b

306 ms ± 15.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [10]:
a_gpu = a.to('cuda')
b_gpu = b.to('cuda')
%timeit c_gpu = a_gpu + b_gpu

The slowest run took 4.41 times longer than the fastest. This could mean that an intermediate result is being cached.
15.6 µs ± 9.57 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [18]:
a = torch.arange(6)
# print(a)
# print(a.shape)
# print(a.view(2, 3))
print(a.reshape(2, 3))

tensor([[0, 1, 2],
        [3, 4, 5]])


In [25]:
a = torch.rand(2, 3, 4)
# print(a, '\n')
# print(a.mT, '\n')
# print(a.permute(1, 2, 0))
print(a.permute(1, 2, 0).shape)

torch.Size([3, 4, 2])


In [35]:
a = torch.arange(6).view(3, 2)
print(a)
print(a[None].shape)
print(a[:, None].shape)
print(a[None, :, None].shape)

tensor([[0, 1],
        [2, 3],
        [4, 5]])
torch.Size([1, 3, 2])
torch.Size([3, 1, 2])
torch.Size([1, 3, 1, 2])


In [39]:
a = torch.arange(6).view(3, 2, 1, 1)
# remove last index
print(a.squeeze(-1).shape)
print(a.squeeze(-2).shape)
print(a.squeeze(0).shape)
print(a.squeeze().shape)

torch.Size([3, 2, 1])
torch.Size([3, 2, 1])
torch.Size([3, 2, 1, 1])
torch.Size([3, 2])


In [41]:
a = torch.rand(4, 1)
b = torch.rand(1, 5)
print(a + b)

tensor([[0.7367, 0.5177, 0.4988, 0.5919, 0.0253],
        [1.4568, 1.2379, 1.2190, 1.3121, 0.7455],
        [0.9643, 0.7454, 0.7264, 0.8196, 0.2530],
        [0.9673, 0.7483, 0.7294, 0.8225, 0.2559]])


In [45]:
a = torch.arange(4).view(4, 1)
b = torch.arange(5).view(1, 5) * 10
print(f'{a = }')
print(f'{b = }')
print(a - b)

a = tensor([[0],
        [1],
        [2],
        [3]])
b = tensor([[ 0, 10, 20, 30, 40]])
tensor([[  0, -10, -20, -30, -40],
        [  1,  -9, -19, -29, -39],
        [  2,  -8, -18, -28, -38],
        [  3,  -7, -17, -27, -37]])


In [52]:
x = torch.randn(10, 2)
d = torch.zeros(10, 10)

# for i in range(10):
#     for j in range(10):
#         d[i, j] = (x[i] - x[j]).pow(2).sum()
# print(d)

# equivalent to nested for loop above
d = (x[:, None, :] - x[None, :, :]).pow(2).sum(-1)
print(d)

tensor([[0.0000e+00, 1.2897e-01, 1.7387e+00, 1.4241e+00, 8.1280e+00, 7.7539e+00,
         3.7374e+00, 1.0956e+00, 1.1147e+00, 7.6592e+00],
        [1.2897e-01, 0.0000e+00, 9.3070e-01, 2.2426e+00, 1.0273e+01, 9.8526e+00,
         3.5605e+00, 1.6968e+00, 1.9876e+00, 6.3061e+00],
        [1.7387e+00, 9.3070e-01, 0.0000e+00, 5.3946e+00, 1.6996e+01, 1.6461e+01,
         3.6392e+00, 4.2363e+00, 5.4766e+00, 3.3050e+00],
        [1.4241e+00, 2.2426e+00, 5.3946e+00, 0.0000e+00, 3.4534e+00, 3.2275e+00,
         3.3059e+00, 1.0265e-01, 2.5960e-01, 1.0430e+01],
        [8.1280e+00, 1.0273e+01, 1.6996e+01, 3.4534e+00, 0.0000e+00, 4.4429e-03,
         1.2368e+01, 4.7172e+00, 3.2237e+00, 2.5522e+01],
        [7.7539e+00, 9.8526e+00, 1.6461e+01, 3.2275e+00, 4.4429e-03, 0.0000e+00,
         1.2005e+01, 4.4561e+00, 2.9900e+00, 2.4947e+01],
        [3.7374e+00, 3.5605e+00, 3.6392e+00, 3.3059e+00, 1.2368e+01, 1.2005e+01,
         0.0000e+00, 2.3216e+00, 4.9613e+00, 2.6828e+00],
        [1.0956e+00, 1.6968

In [59]:
x = torch.randn(10, 2)
d = torch.zeros(10, 10)
max_dist, max_idx = 0, (-1, -1)

for i in range(10):
    for j in range(10):
        if (x[i] - x[j]).pow(2).sum() > max_dist:
            max_dist, max_idx = (x[i] - x[j]).pow(2).sum(), (i, j)
print(max_dist, max_idx)

d = (x[:, None, :] - x[None, :, :]).pow(2).sum(-1)
print(d.max(), (d.argmax() // 10, d.argmax() % 10))

tensor(22.0544) (4, 7)
tensor(22.0544) (tensor(4), tensor(7))


In [62]:
a = torch.rand(2, 4)
b = torch.rand(4, 3)
c = a @ b
print(c)
print(c.shape)

tensor([[0.5893, 1.0178, 0.8676],
        [0.5194, 0.4649, 0.3327]])
torch.Size([2, 3])


In [68]:
a = torch.rand(2, 4)
b = torch.rand(4)
c = b @ a.mT
print(c.shape)
print(torch.linalg.norm(b))

# equivalent to above linalg call
print(b.pow(2).sum().sqrt())

torch.Size([2])
tensor(1.3223)
tensor(1.3223)
