## Lecture 2.3: Loss Functions in PyTorch

In [2]:
import torch

In [3]:
model = torch.nn.Linear(10, 1)

In [4]:
x = torch.randn(20, 10)
y = torch.randn(20, 1)
print(f'{x=} {y=}')

x=tensor([[-1.7157,  0.2723,  0.2605,  0.8049,  0.9360,  0.1178, -1.1467, -1.0958,
          0.1131, -0.7971],
        [-0.2133,  1.5616, -0.5865,  2.0435,  2.0033,  0.2643, -0.1744, -0.1345,
         -0.8995, -0.7836],
        [ 0.2003,  0.8282,  0.3317,  0.1174, -0.9056,  0.0381, -0.2074, -0.0956,
         -0.0346, -0.3876],
        [-0.9700,  1.0799,  0.7568, -0.2424,  1.5821, -0.9750, -1.6852,  0.1128,
          0.5962, -0.6789],
        [-0.7722,  0.7714,  1.2839, -0.4485,  0.5791,  0.9248, -0.9611,  0.1641,
          0.4762,  0.6230],
        [-0.1726,  1.5206, -0.5802,  0.1347, -0.7945, -1.4778,  2.1264, -0.5404,
         -0.0097,  0.2387],
        [ 0.4563,  0.6463, -1.0185, -0.9843, -0.9828, -0.1481,  0.5168, -0.4819,
          0.2391,  0.1521],
        [-1.4396, -0.9947, -0.0126,  0.7578, -1.7899, -2.2030, -0.4822, -0.3504,
          2.1288, -1.7539],
        [-0.0904,  0.0320,  0.8591,  0.7712, -0.8886, -1.3279,  2.4753,  0.0827,
         -0.5207, -1.1707],
        [-0.5746,

In [6]:
pred_y = model(x)
print(pred_y)

tensor([[-0.4766],
        [-0.5957],
        [ 0.0404],
        [ 0.2184],
        [-0.2866],
        [ 0.2843],
        [ 0.5203],
        [ 0.7052],
        [-0.2060],
        [-0.1365],
        [ 0.7983],
        [-0.2766],
        [ 0.8562],
        [ 0.4079],
        [ 0.1365],
        [ 0.6993],
        [ 0.0924],
        [ 0.1332],
        [ 0.9500],
        [ 0.5460]], grad_fn=<AddmmBackward0>)


In [7]:
# y, pred_y
loss = torch.nn.functional.mse_loss(pred_y, y)
print(loss)

tensor(1.3845, grad_fn=<MseLossBackward0>)


In [8]:
def mse_loss(pred_y, y):
    return torch.mean((pred_y - y) ** 2)

mse_loss(pred_y, y)

tensor(1.3845, grad_fn=<MeanBackward0>)

In [13]:
y = (torch.randn(20, 1) > 0).float()
print(y)

tensor([[1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.]])


In [15]:
# if loss > 0.7, the model would be better if we flipped the labels
# if loss < 0.7 then the model is good
loss = torch.nn.functional.binary_cross_entropy_with_logits(pred_y, y)
print(loss)

tensor(0.7947, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)


In [24]:
n_classes = 3
model = torch.nn.Linear(10, n_classes)
# y = (torch.randn(20) > 0).long() + (torch.randn(20) > 0).long() didnt work from lecture
y = torch.randint(0, n_classes, (20,)) # this worked
print(y)

tensor([0, 1, 2, 1, 2, 0, 1, 2, 0, 1, 2, 2, 0, 1, 1, 2, 2, 0, 2, 2])


In [26]:
pred_y = model(x)
loss = torch.nn.functional.cross_entropy(pred_y, y)
print(loss)

tensor(1.1144, grad_fn=<NllLossBackward0>)
